# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: fblog
      POSTGRES_PASSWORD: fblog
      POSTGRES_DB: fb
    ports:
      - 5432:5432
    volumes:
      - ./database-data:/var/lib/postgresql/data/


  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

# volumes:
#   pgadmin-data:

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080